[package]
name = "skidmark"
version = "2026.8.27"
edition = "2021"
repository = "https://github.com/Tholp1/Skidmark" # for cargo-dist, also available at https://tangled.org/@tholps.site/skidmark

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.40", features = ["derive"] }
colored = "3.0.0"
glob = "0.3.2"
markdown = "1.0.0"
mlua = { version = "0.11.6", features = [ "lua54", "vendored" ] }
serde = "1.0.218"
toml = "0.8.19"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
